## YAML Template.
---

zuul:
    routes:
        greetings:
            path: /reservations/**
            serviceId: MICROSERVICE-RESERVATION
            stripPrefix: false
eureka:
    client:
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://localhost:1111/eureka
server:
    port: 8080 # HTTP (Tomcat) port