## YAML Template.
---
eureka:
    instance:
        hostname: localhost
    client: # Not a client, don't register with yourself
        registerWithEureka: false
        fetchRegistry: false
        
    server:
        port: 1111 # HTTP (Tomcat) port
        enableSelfPreservation: false
        
    spring:
        thymeleaf:
            enable: false # Disable Thymeleaf