---
spring:
    application: 
        name: microservice-reservation
    freemaker:
        enable: false
    thymeleaf: 
        cache : false
        prefix: classpath:/templates
    h2:
        console:
            enable: true
eureka: 
    client: 
        serviceUrl:
            defaultZone: http://localhost:1111/eureka
        healthcheck:
            enable: true
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
server:
    port:2222
        